### PR TITLE
Double buffer fixes

### PR DESCRIPTION
**Pull request by Rasmusfk**
All Adafruit draw functions now work with double buffering, and using double buffer is simpler.

### CODE REVIEW

**Comment by Rasmusfk** [comment]
This also solves issue #91 by the way.

**Comment by 2dom** [comment]
Ok ... merged this one. Looks ok to me - don't have time to test though (hope nothing blows up :)

**Comment by witnessmenow** [comment]
Hey @2dom , I tested @Rasmusfk branch, and I saw a negative effect on performance. I'm not sure am I using it wrong or what happened, but the difference is significantly worse.

https://twitter.com/witnessmenow/status/1135343801386618886

Display on the right is the one with the double buffer enabled.

Code is the exact same other than how it is displayed

Significant code below:

tetris.drawXXX() draws on the screen using GFX methods (drawFilledRect etc)

```

#define double_buffer

animationTimer = timerBegin(1, 80, true);
  timerAttachInterrupt(animationTimer, &animationHandler, true);
  timerAlarmWrite(animationTimer, 100000, true);
  timerAlarmEnable(animationTimer);


void animationHandler()
{
  portENTER_CRITICAL_ISR(&timerMux);

  // Not clearing the display and redrawing it when you
  // dont need to improves how the refresh rate appears
  if (!finishedAnimating) {
#ifdef double_buffer
    display.fillScreen(tetris.tetrisBLACK);
#else
    display.clearDisplay();
#endif
    //display.fillScreen(tetris.tetrisBLACK);
    if (displayIntro) {
      finishedAnimating = tetris.drawText(1, 21);
    } else {
      if (twelveHourFormat) {
        // Place holders for checking are any of the tetris objects
        // currently still animating.
        bool tetris1Done = false;
        bool tetris2Done = false;
        bool tetris3Done = false;

        tetris1Done = tetris.drawNumbers(-6, 26, showColon);
        tetris2Done = tetris2.drawText(56, 25);

        // Only draw the top letter once the bottom letter is finished.
        if (tetris2Done) {
          tetris3Done = tetris3.drawText(56, 15);
        }

        finishedAnimating = tetris1Done && tetris2Done && tetris3Done;

      } else {
        finishedAnimating = tetris.drawNumbers(2, 26, showColon);
      }
    }
#ifdef double_buffer
    display.showBuffer();
#endif
  }
  portEXIT_CRITICAL_ISR(&timerMux);
}

```

**Comment by Rasmusfk** [comment]
Hi @witnessmenow 
Are you doing the drawing inside an interrupt? This would explain the worse behaviour (flickering), as the display.showBuffer() call assumes that it is not called from an interrupt. 
Regards

**Comment by witnessmenow** [comment]
Hi @Rasmusfk ,

Here is my sketch here:
https://github.com/witnessmenow/WiFi-Tetris-Clock/blob/master/ESP32%20or%20TinyPICO/EzTimeTetrisClockESP32/EzTimeTetrisClockESP32.ino

Currently it is drawing inside of a timer event, so would the recommended approach be to do this in the loop instead?

**Comment by witnessmenow** [comment]
That would be great! I wont be able to take a look at it again for a while.

A couple of things that might be weird in the sketch:

- Search for "Generic" and uncomment does lines and comment out the "TinyPICO" lines beside them. The TinyPICO doesnt have pin 13 or pin 2 broken out so I needed to make some changes to get it to work.
- [This while loop](https://github.com/witnessmenow/WiFi-Tetris-Clock/blob/master/ESP32%20or%20TinyPICO/EzTimeTetrisClockESP32/EzTimeTetrisClockESP32.ino#L263) might prevent it working if you move the animation to the loop, don't worry about it and just comment it out

**Comment by Rasmusfk** [comment]
Hi again @witnessmenow 

Before I do anything, could you please try to comment out all the lines containing portENTER_CRITICAL_ISR(&timerMux) and portEXIT_CRITICAL_ISR(&timerMux)
With the double-buffering the mutex isn't necessary, and I think that may cause the flickering.
Regards

**Comment by witnessmenow** [comment]
I tried that by adding 

```
#ifndef double_buffer
  portENTER_CRITICAL_ISR(&timerMux);
#endif
```

but it didn't improve the flicker

**Comment by Rasmusfk** [comment]
Ok, I'll try to run the sketch myself tonight and see if I can figure out what's wrong.

**Comment by maciejmatczak** [comment]
@witnessmenow, I would start with moving:
```C
#define double_buffer
```
before including PxMatrix header file. I would assume, that without this the library is built without double_buffer functionality. But even knowing that, I cannot pinpoint the place that it should give such results. 

You actually do switch in this case the internal _active_buffer variable with showBuffer, but if PxMatrix is built without this support, everything else seems to be hardcoded to use only one buffer.

@Rasmusfk, what do you think?

**Comment by witnessmenow** [comment]
I thought that might be a problem so I tried it before too but it didn't
make a difference.

**Comment by maciejmatczak** [comment]
@witnessmenow Any chance to reproduce issue on esp8266 with minimal implementation?

**Comment by witnessmenow** [comment]
The repo has an esp8266 version in it, but it's kernal panicking when it
gets to the loop, I need to investigate it at some stage.

But the basic examples contained in the library do work, so might be enough
to reproduce the issue on an esp8266, but I wouldn't be able to spend any
time on it for the next while

https://github.com/toblum/TetrisAnimation

**Comment by 2dom** [comment]
is this resolved ? (accidentally closed this one)

**Comment by Rasmusfk** [comment]
Hi @witnessmenow 

So I got time to look at your issue. To fix it, the display.display() should remain in an interrupt, but the animation part should be moved either into the regular Arduino "loop()", or to a callback that is not called in an interrupt context. I've forked your code and implemented the last option in:
https://github.com/Rasmusfk/WiFi-Tetris-Clock
It runs smoothly and flicker-free for me - Could you give it a try?

I'll try to add an explanation of how the double-buffering is best used and an example and send a pull-request to @2dom, as it can be a little hard to grasp all that interrupt and callback-stuff.
Regards

**Comment by witnessmenow** [comment]
Just tried it there @Rasmusfk , huge improvement over my version using it! And a noticeable reduction in flicker over not using it, I'll record a video with a side by side if I can (although its hard to record them as the camera can flicker too!)

**Pull request merged**
