### PR TITLE
Remove max size static buffer

### PR DESCRIPTION
**Pull request by opticron**
This removes the limitation of maximum total display size.

### CODE REVIEW

**Comment by lucianolopesjardim** [comment]
Hey guys, congratulations for this great library, I'm trying to use 8 panels P10 32x16 1/2 scan (256x16) with no luck.. After some tricks got 4 panels working (128x16) . Do you think this patch can let me use 8 panels? Thanks.

**Comment by lucianolopesjardim** [comment]
Hey guys, congratulations for this great library, I'm trying to use 8 panels P10 32x16 1/2 scan (256x16) with no luck.. After some tricks got 4 panels working (128x16) . Do you think this patch can let me use 8 panels? Thanks.

**Comment by opticron** [comment]
@lucianolopesjardim This patch removes the static buffer allocation that limits displays to 64x64 by default, but you can always change those hard-coded values to something larger. If you can't get an 8 panel chain working, open a new issue with a description of the symptoms and a video of the test pattern running.

**Comment by 2dom** [comment]
We went a different route since I prefer static allocation. The max size of the matrix can now be set via appropriate defines in the ino file

**Pull request closed without merging**
