### PR TITLE
Add WZAGZIG and VZAG scan patterns

### PR DESCRIPTION
**Pull request by opticron**
These new scan patterns have been implemented as X/Y pre-transformations so that they'll be easier to understand and maintain in the future. I'd eventually like to migrate the other scan patterns to X/Y transformations as well, but I don't have the panels to verify solutions.

### CODE REVIEW

**Comment by opticron** [comment]
Alright, this is now updated for the latest changes to make VZAG work properly.

**Comment by 2dom** [comment]
cool ... can i just merge this? zero time to review....

**Comment by opticron** [comment]
Yep, it's ready to merge.

**Comment by 2dom** [comment]
done ... thanks for all the effort!

**Pull request merged**
