### PR TITLE
Adding the ability overide the SPI pins

### PR DESCRIPTION
**Pull request by witnessmenow**
A potential fix for #105 

Don't merge yet, if you are happy with the approach I can add an example, and update the readme if required.

### CODE REVIEW

**Comment by witnessmenow** [comment]
Usage: 

```
//begin(uint8_t row_pattern, uint8_t CLK, uint8_t MOSI, uint8_t MISO, uint8_t SS)
display.begin(16, SPI_BUS_CLK, 27, SPI_BUS_MISO, SPI_BUS_SS);
```

Tested with both a regular wiring setup and a modified one (using pin 27 for MOSI)

**Comment by 2dom** [comment]
Looking good to me ... if you would add an example etc. it would be perfect

**Comment by witnessmenow** [comment]
Cool, I'll add an example this evening!

**Comment by witnessmenow** [comment]
Added an example @2dom , its just pixel time but adjust for the TinyPICO as an example. Added a comment to the top of the example explaining what it

**Comment by 2dom** [comment]
Thanks man ... looking good

**Pull request merged**
