### PR TITLE
fix latch_time in fast_update

### PR DESCRIPTION
**Pull request by xsrf**
In fast_update the latch_time is wrong for the first iteration. It should match the latch_time of the previous iteration because in fast_update always the previous buffer is shown.

also fixes issues caused by latching while output is enabled in fast_update.

### CODE REVIEW

**Comment by xsrf** [comment]
Also added a bounds check for `PxMATRIX_COLOR_DEPTH` because existing code may have used more

**Comment by 2dom** [comment]
Thanks ... I missed that one!

**Comment by 2dom** [comment]
OK ... there were actually a few more conceptual issues with my code. Wanna try out the latest master?

**Comment by xsrf** [comment]
sure, see comment on 9df6dc6 :)

**Pull request merged**
